#!/usr/bin/env bash

# Change this to your default VAGRANT_ENV
DEFAULT_VAGRANT_ENV='main'

[ -z "$VAGRANT_ENV" ] && export VAGRANT_ENV=$DEFAULT_VAGRANT_ENV
export VAGRANT_DOTFILE_PATH=".vagrant_${HOSTNAME}_${VAGRANT_ENV}"
export THYVAGRANT=YES


echo "Vagrant environment: ${VAGRANT_ENV}"
vagrant "$@"

